# Site settings

title: ChatterBot
email: community@chatterbot.us
description: >- # this means to ignore newlines until "baseurl:"
  ChatterBot is a machine-learning based conversational dialog engine built in
  Python which makes it possible to generate responses based on collections of
  known conversations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chatterbot.us" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gunthercox
github_username:  gunthercox

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:year/:month/:title

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
